services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db/erp_v2.db:/app/db/erp_v2.db
    environment:
      - API_URL=http://backend:8000/api

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api/chat
    depends_on:
      - backend
